apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flask-book-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-book-app
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50